<?php // https://github.com/alcohol/iso4217/blob/main/ISO4217.php
return collect([
    [
        'name' => 'UAE Dirham',
        'alpha' => 'AED',
        'numeric' => '784',
        'symbol' => 'د.إ',
        'exp' => 2,
        'country' => 'AE',
    ],
    [
        'name' => 'Afghan Afghani',
        'alpha' => 'AFN',
        'numeric' => '971',
        'symbol' => '؋',
        'exp' => 2,
        'country' => 'AF',
    ],
    [
        'name' => 'Albanian Lek',
        'alpha' => 'ALL',
        'numeric' => '008',
        'symbol' => 'ALL',
        'exp' => 2,
        'country' => 'AL',
    ],
    [
        'name' => 'Armenian Dram',
        'alpha' => 'AMD',
        'numeric' => '051',
        'symbol' => 'AMD',
        'exp' => 2,
        'country' => 'AM',
    ],
    [
        'name' => 'Netherlands Antillean Guilder',
        'alpha' => 'ANG',
        'numeric' => '532',
        'symbol' => 'ƒ',
        'exp' => 2,
        'country' => [
            'CW',
            'SX',
        ],
    ],
    [
        'name' => 'Angolan Kwanza',
        'alpha' => 'AOA',
        'numeric' => '973',
        'symbol' => 'AOA',
        'exp' => 2,
        'country' => 'AO',
    ],
    [
        'name' => 'Argentine Peso',
        'alpha' => 'ARS',
        'numeric' => '032',
        'symbol' => 'Arg$',
        'exp' => 2,
        'country' => 'AR',
    ],
    [
        'name' => 'Australian Dollar',
        'alpha' => 'AUD',
        'numeric' => '036',
        'symbol' => 'A$',
        'exp' => 2,
        'country' => [
            'AU',
            'CC',
            'CX',
            'HM',
            'KI',
            'NF',
            'NR',
            'TV',
        ],
    ],
    [
        'name' => 'Aruban Florin',
        'alpha' => 'AWG',
        'numeric' => '533',
        'symbol' => 'Aƒ',
        'exp' => 2,
        'country' => 'AW',
    ],
    [
        'name' => 'Azerbaijani Manat',
        'alpha' => 'AZN',
        'numeric' => '944',
        'symbol' => '₼',
        'exp' => 2,
        'country' => 'AZ',
    ],
    [
        'name' => 'Bosnia and Herzegovina Convertible Mark',
        'alpha' => 'BAM',
        'numeric' => '977',
        'symbol' => 'BAM',
        'exp' => 2,
        'country' => 'BA',
    ],
    [
        'name' => 'Barbados Dollar',
        'alpha' => 'BBD',
        'numeric' => '052',
        'symbol' => 'Bds$',
        'exp' => 2,
        'country' => 'BB',
    ],
    [
        'name' => 'Bangladeshi Taka',
        'alpha' => 'BDT',
        'numeric' => '050',
        'symbol' => '৳',
        'exp' => 2,
        'country' => 'BD',
    ],
    [
        'name' => 'Bulgarian Lev',
        'alpha' => 'BGN',
        'numeric' => '975',
        'symbol' => 'BGN',
        'exp' => 2,
        'country' => 'BG',
    ],
    [
        'name' => 'Bahraini Dinar',
        'alpha' => 'BHD',
        'numeric' => '048',
        'symbol' => '.د.ب',
        'exp' => 3,
        'country' => 'BH',
    ],
    [
        'name' => 'Burundian Franc',
        'alpha' => 'BIF',
        'numeric' => '108',
        'symbol' => '₣Bu',
        'exp' => 0,
        'country' => 'BI',
    ],
    [
        'name' => 'Bermudian Dollar',
        'alpha' => 'BMD',
        'numeric' => '060',
        'symbol' => 'Ber$',
        'exp' => 2,
        'country' => 'BM',
    ],
    [
        'name' => 'Brunei Dollar',
        'alpha' => 'BND',
        'numeric' => '096',
        'symbol' => 'BR$',
        'exp' => 2,
        'country' => 'BN',
    ],
    [
        'name' => 'Boliviano',
        'alpha' => 'BOB',
        'numeric' => '068',
        'symbol' => 'BOB',
        'exp' => 2,
        'country' => 'BO',
    ],
    [
        'name' => 'Brazilian Real',
        'alpha' => 'BRL',
        'numeric' => '986',
        'symbol' => 'R$',
        'exp' => 2,
        'country' => 'BR',
    ],
    [
        'name' => 'Bahamian Dollar',
        'alpha' => 'BSD',
        'numeric' => '044',
        'symbol' => 'B$',
        'exp' => 2,
        'country' => 'BS',
    ],
    [
        'name' => 'Bhutanese Ngultrum',
        'alpha' => 'BTN',
        'numeric' => '064',
        'symbol' => 'BTN',
        'exp' => 2,
        'country' => 'BT',
    ],
    [
        'name' => 'Botswana Pula',
        'alpha' => 'BWP',
        'numeric' => '072',
        'symbol' => 'BWP',
        'exp' => 2,
        'country' => [
            'BW',
            'ZW',
        ],
    ],
    [
        'name' => 'Belarussian Ruble',
        'alpha' => 'BYN',
        'numeric' => '933',
        'symbol' => 'B₽',
        'exp' => 2,
        'country' => 'BY',
    ],
    [
        'name' => 'Belize Dollar',
        'alpha' => 'BZD',
        'numeric' => '084',
        'symbol' => 'BZ$',
        'exp' => 2,
        'country' => 'BZ',
    ],
    [
        'name' => 'Canadian Dollar',
        'alpha' => 'CAD',
        'numeric' => '124',
        'symbol' => 'C$',
        'exp' => 2,
        'country' => 'CA',
    ],
    [
        'name' => 'Congolese Franc',
        'alpha' => 'CDF',
        'numeric' => '976',
        'symbol' => '₣C',
        'exp' => 2,
        'country' => 'CD',
    ],
    [
        'name' => 'Swiss Franc',
        'alpha' => 'CHF',
        'numeric' => '756',
        'symbol' => 'S₣',
        'exp' => 2,
        'country' => [
            'CH',
            'LI',
        ],
    ],
    [
        'name' => 'Chilean Peso',
        'alpha' => 'CLP',
        'numeric' => '152',
        'symbol' => 'Ch$',
        'exp' => 0,
        'country' => 'CL',
    ],
    [
        'name' => 'Chinese Yuan',
        'alpha' => 'CNY',
        'numeric' => '156',
        'symbol' => '¥',
        'exp' => 2,
        'country' => 'CN',
    ],
    [
        'name' => 'Colombian Peso',
        'alpha' => 'COP',
        'numeric' => '170',
        'symbol' => 'Col$',
        'exp' => 2,
        'country' => 'CO',
    ],
    [
        'name' => 'Costa Rican Colon',
        'alpha' => 'CRC',
        'numeric' => '188',
        'symbol' => '₡',
        'exp' => 2,
        'country' => 'CR',
    ],
    [
        'name' => 'Cuban Convertible Peso',
        'alpha' => 'CUC',
        'numeric' => '931',
        'symbol' => 'CUC',
        'exp' => 2,
        'country' => 'CU',
    ],
    [
        'name' => 'Cuban Peso',
        'alpha' => 'CUP',
        'numeric' => '192',
        'symbol' => 'CUP',
        'exp' => 2,
        'country' => 'CU',
    ],
    [
        'name' => 'Cape Verde Escudo',
        'alpha' => 'CVE',
        'numeric' => '132',
        'symbol' => 'CVE',
        'exp' => 2,
        'country' => 'CV',
    ],
    [
        'name' => 'Czech Koruna',
        'alpha' => 'CZK',
        'numeric' => '203',
        'symbol' => 'CZK',
        'exp' => 2,
        'country' => 'CZ',
    ],
    [
        'name' => 'Djiboutian Franc',
        'alpha' => 'DJF',
        'numeric' => '262',
        'symbol' => 'D₣',
        'exp' => 0,
        'country' => 'DJ',
    ],
    [
        'name' => 'Danish Krone',
        'alpha' => 'DKK',
        'numeric' => '208',
        'symbol' => 'DKK',
        'exp' => 2,
        'country' => [
            'DK',
            'FO',
            'GL',
        ],
    ],
    [
        'name' => 'Dominican Peso',
        'alpha' => 'DOP',
        'numeric' => '214',
        'symbol' => 'DOP',
        'exp' => 2,
        'country' => 'DO',
    ],
    [
        'name' => 'Algerian Dinar',
        'alpha' => 'DZD',
        'numeric' => '012',
        'symbol' => '.د.ج',
        'exp' => 2,
        'country' => 'DZ',
    ],
    [
        'name' => 'Egyptian Pound',
        'alpha' => 'EGP',
        'numeric' => '818',
        'symbol' => '.ج.م',
        'exp' => 2,
        'country' => 'EG',
    ],
    [
        'name' => 'Eritrean Nakfa',
        'alpha' => 'ERN',
        'numeric' => '232',
        'symbol' => 'ERN',
        'exp' => 2,
        'country' => 'ER',
    ],
    [
        'name' => 'Ethiopian Birr',
        'alpha' => 'ETB',
        'numeric' => '230',
        'symbol' => 'ETB',
        'exp' => 2,
        'country' => 'ET',
    ],
    [
        'name' => 'Euro',
        'alpha' => 'EUR',
        'numeric' => '978',
        'symbol' => '€',
        'exp' => 2,
        'country' => [
            'AD',
            'AT',
            'AX',
            'BE',
            'BL',
            'CY',
            'DE',
            'EE',
            'ES',
            'FI',
            'FR',
            'GF',
            'GP',
            'GR',
            'IE',
            'IT',
            'LT',
            'LV',
            'LU',
            'MC',
            'ME',
            'MF',
            'MQ',
            'MT',
            'NL',
            'PM',
            'PT',
            'RE',
            'SI',
            'SK',
            'SM',
            'TF',
            'VA',
            'YT',
            'ZW',
        ],
    ],
    [
        'name' => 'Fiji Dollar',
        'alpha' => 'FJD',
        'numeric' => '242',
        'symbol' => 'FJ$',
        'exp' => 2,
        'country' => 'FJ',
    ],
    [
        'name' => 'Falkland Islands Pound',
        'alpha' => 'FKP',
        'numeric' => '238',
        'symbol' => 'FKP',
        'exp' => 2,
        'country' => 'FK',
    ],
    [
        'name' => 'Pound Sterling',
        'alpha' => 'GBP',
        'numeric' => '826',
        'symbol' => '£',
        'exp' => 2,
        'country' => [
            'GB',
            'GG',
            'GS',
            'IM',
            'IO',
            'JE',
            'ZW',
        ],
    ],
    [
        'name' => 'Georgian Lari',
        'alpha' => 'GEL',
        'numeric' => '981',
        'symbol' => 'GEL',
        'exp' => 2,
        'country' => 'GE',
    ],
    [
        'name' => 'Ghanaian Cedi',
        'alpha' => 'GHS',
        'numeric' => '936',
        'symbol' => '₵',
        'exp' => 2,
        'country' => 'GH',
    ],
    [
        'name' => 'Gibraltar Pound',
        'alpha' => 'GIP',
        'numeric' => '292',
        'symbol' => 'GIP',
        'exp' => 2,
        'country' => 'GI',
    ],
    [
        'name' => 'Gambian Dalasi',
        'alpha' => 'GMD',
        'numeric' => '270',
        'symbol' => 'GMD',
        'exp' => 2,
        'country' => 'GM',
    ],
    [
        'name' => 'Guinean Franc',
        'alpha' => 'GNF',
        'numeric' => '324',
        'symbol' => 'G₣',
        'exp' => 0,
        'country' => 'GN',
    ],
    [
        'name' => 'Guatemalan Quetzal',
        'alpha' => 'GTQ',
        'numeric' => '320',
        'symbol' => 'GTQ',
        'exp' => 2,
        'country' => 'GT',
    ],
    [
        'name' => 'Guyanese Dollar',
        'alpha' => 'GYD',
        'numeric' => '328',
        'symbol' => 'G$',
        'exp' => 2,
        'country' => 'GY',
    ],
    [
        'name' => 'Hong Kong Dollar',
        'alpha' => 'HKD',
        'numeric' => '344',
        'symbol' => 'HK$',
        'exp' => 2,
        'country' => 'HK',
    ],
    [
        'name' => 'Honduran Lempira',
        'alpha' => 'HNL',
        'numeric' => '340',
        'symbol' => 'HNL',
        'exp' => 2,
        'country' => 'HN',
    ],
    [
        'name' => 'Kuna',
        'alpha' => 'HRK',
        'numeric' => '191',
        'symbol' => 'HRK',
        'exp' => 2,
        'country' => 'HR',
    ],
    [
        'name' => 'Haitian Gourde',
        'alpha' => 'HTG',
        'numeric' => '332',
        'symbol' => 'HTG',
        'exp' => 2,
        'country' => 'HT',
    ],
    [
        'name' => 'Hungarian Forint',
        'alpha' => 'HUF',
        'numeric' => '348',
        'symbol' => 'HUF',
        'exp' => 2,
        'country' => 'HU',
    ],
    [
        'name' => 'Indonesian Rupiah',
        'alpha' => 'IDR',
        'numeric' => '360',
        'symbol' => 'IDR',
        'exp' => 2,
        'country' => 'ID',
    ],
    [
        'name' => 'Israeli New Sheqel',
        'alpha' => 'ILS',
        'numeric' => '376',
        'symbol' => '₪',
        'exp' => 2,
        'country' => [
            'IL',
            'PS',
        ],
    ],
    [
        'name' => 'Indian Rupee',
        'alpha' => 'INR',
        'numeric' => '356',
        'symbol' => '₹',
        'exp' => 2,
        'country' => 'IN',
    ],
    [
        'name' => 'Iraqi Dinar',
        'alpha' => 'IQD',
        'numeric' => '368',
        'symbol' => '.د.ع',
        'exp' => 3,
        'country' => 'IQ',
    ],
    [
        'name' => 'Iranian Rial',
        'alpha' => 'IRR',
        'numeric' => '364',
        'symbol' => '﷼',
        'exp' => 2,
        'country' => 'IR',
    ],
    [
        'name' => 'Icelandic Króna',
        'alpha' => 'ISK',
        'numeric' => '352',
        'symbol' => 'ISK',
        'exp' => 0,
        'country' => 'IS',
    ],
    [
        'name' => 'Jamaican Dollar',
        'alpha' => 'JMD',
        'numeric' => '388',
        'symbol' => 'J$',
        'exp' => 2,
        'country' => 'JM',
    ],
    [
        'name' => 'Jordanian Dinar',
        'alpha' => 'JOD',
        'numeric' => '400',
        'symbol' => '.د.أ',
        'exp' => 3,
        'country' => 'JO',
    ],
    [
        'name' => 'Japanese Yen',
        'alpha' => 'JPY',
        'numeric' => '392',
        'symbol' => 'J¥',
        'exp' => 0,
        'country' => 'JP',
    ],
    [
        'name' => 'Kenyan Shilling',
        'alpha' => 'KES',
        'numeric' => '404',
        'symbol' => 'KES',
        'exp' => 2,
        'country' => 'KE',
    ],
    [
        'name' => 'Kyrgyzstani Som',
        'alpha' => 'KGS',
        'numeric' => '417',
        'symbol' => 'KGS',
        'exp' => 2,
        'country' => 'KG',
    ],
    [
        'name' => 'Cambodian Riel',
        'alpha' => 'KHR',
        'numeric' => '116',
        'symbol' => '៛',
        'exp' => 2,
        'country' => 'KH',
    ],
    [
        'name' => 'Comoro Franc',
        'alpha' => 'KMF',
        'numeric' => '174',
        'symbol' => 'KMF',
        'exp' => 0,
        'country' => 'KM',
    ],
    [
        'name' => 'North Korean Won',
        'alpha' => 'KPW',
        'numeric' => '408',
        'symbol' => 'N₩',
        'exp' => 2,
        'country' => 'KP',
    ],
    [
        'name' => 'South Korean Won',
        'alpha' => 'KRW',
        'numeric' => '410',
        'symbol' => 'S₩',
        'exp' => 0,
        'country' => 'KR',
    ],
    [
        'name' => 'Kuwaiti Dinar',
        'alpha' => 'KWD',
        'numeric' => '414',
        'symbol' => '.د.ك',
        'exp' => 3,
        'country' => 'KW',
    ],
    [
        'name' => 'Cayman Islands Dollar',
        'alpha' => 'KYD',
        'numeric' => '136',
        'symbol' => 'CI$',
        'exp' => 2,
        'country' => 'KY',
    ],
    [
        'name' => 'Kazakhstani Tenge',
        'alpha' => 'KZT',
        'numeric' => '398',
        'symbol' => '₸',
        'exp' => 2,
        'country' => 'KZ',
    ],
    [
        'name' => 'Lao Kip',
        'alpha' => 'LAK',
        'numeric' => '418',
        'symbol' => '₭',
        'exp' => 2,
        'country' => 'LA',
    ],
    [
        'name' => 'Lebanese Pound',
        'alpha' => 'LBP',
        'numeric' => '422',
        'symbol' => '.ل.ل',
        'exp' => 2,
        'country' => 'LB',
    ],
    [
        'name' => 'Sri Lankan Rupee',
        'alpha' => 'LKR',
        'numeric' => '144',
        'symbol' => '₨',
        'exp' => 2,
        'country' => 'LK',
    ],
    [
        'name' => 'Liberian Dollar',
        'alpha' => 'LRD',
        'numeric' => '430',
        'symbol' => 'L$',
        'exp' => 2,
        'country' => 'LR',
    ],
    [
        'name' => 'Lesotho Loti',
        'alpha' => 'LSL',
        'numeric' => '426',
        'symbol' => 'LSL',
        'exp' => 2,
        'country' => 'LS',
    ],
    [
        'name' => 'Latvian Lats',
        'alpha' => 'LVL',
        'numeric' => '428',
        'symbol' => 'LVL',
        'exp' => 2,
        'country' => 'LV',
    ],
    [
        'name' => 'Libyan Dinar',
        'alpha' => 'LYD',
        'numeric' => '434',
        'symbol' => '.د.ل',
        'exp' => 3,
        'country' => 'LY',
    ],
    [
        'name' => 'Moroccan Dirham',
        'alpha' => 'MAD',
        'numeric' => '504',
        'symbol' => '.د.م',
        'exp' => 2,
        'country' => [
            'EH',
            'MA',
        ],
    ],
    [
        'name' => 'Moldovan Leu',
        'alpha' => 'MDL',
        'numeric' => '498',
        'symbol' => 'MDL',
        'exp' => 2,
        'country' => 'MD',
    ],
    [
        'name' => 'Malagasy Ariary',
        'alpha' => 'MGA',
        'numeric' => '969',
        'symbol' => 'MGA',
        'exp' => 2,
        'country' => 'MG',
    ],
    [
        'name' => 'Macedonian Denar',
        'alpha' => 'MKD',
        'numeric' => '807',
        'symbol' => 'MKD',
        'exp' => 2,
        'country' => 'MK',
    ],
    [
        'name' => 'Myanmar Kyat',
        'alpha' => 'MMK',
        'numeric' => '104',
        'symbol' => 'MMK',
        'exp' => 2,
        'country' => 'MM',
    ],
    [
        'name' => 'Mongolian Tugrik',
        'alpha' => 'MNT',
        'numeric' => '496',
        'symbol' => '₮',
        'exp' => 2,
        'country' => 'MN',
    ],
    [
        'name' => 'Macanese Pataca',
        'alpha' => 'MOP',
        'numeric' => '446',
        'symbol' => 'MOP',
        'exp' => 2,
        'country' => 'MO',
    ],
    [
        'name' => 'Mauritanian Ouguiya',
        'alpha' => 'MRU',
        'numeric' => '929',
        'symbol' => 'MRU',
        'exp' => 2,
        'country' => 'MR',
    ],
    [
        'name' => 'Mauritian Rupee',
        'alpha' => 'MUR',
        'numeric' => '480',
        'symbol' => 'MUR',
        'exp' => 2,
        'country' => 'MU',
    ],
    [
        'name' => 'Maldivian Rufiyaa',
        'alpha' => 'MVR',
        'numeric' => '462',
        'symbol' => 'ރ',
        'exp' => 2,
        'country' => 'MV',
    ],
    [
        'name' => 'Malawian Kwacha',
        'alpha' => 'MWK',
        'numeric' => '454',
        'symbol' => 'MWK',
        'exp' => 2,
        'country' => 'MW',
    ],
    [
        'name' => 'Mexican Peso',
        'alpha' => 'MXN',
        'numeric' => '484',
        'symbol' => 'Mex$',
        'exp' => 2,
        'country' => 'MX',
    ],
    [
        'name' => 'Malaysian Ringgit',
        'alpha' => 'MYR',
        'numeric' => '458',
        'symbol' => 'MYR',
        'exp' => 2,
        'country' => 'MY',
    ],
    [
        'name' => 'Mozambican Metical',
        'alpha' => 'MZN',
        'numeric' => '943',
        'symbol' => 'MZN',
        'exp' => 2,
        'country' => 'MZ',
    ],
    [
        'name' => 'Namibian Dollar',
        'alpha' => 'NAD',
        'numeric' => '516',
        'symbol' => 'N$',
        'exp' => 2,
        'country' => 'NA',
    ],
    [
        'name' => 'Nigerian Naira',
        'alpha' => 'NGN',
        'numeric' => '566',
        'symbol' => '₦',
        'exp' => 2,
        'country' => 'NG',
    ],
    [
        'name' => 'Nicaraguan Córdoba',
        'alpha' => 'NIO',
        'numeric' => '558',
        'symbol' => 'C$',
        'exp' => 2,
        'country' => 'NI',
    ],
    [
        'name' => 'Norwegian Krone',
        'alpha' => 'NOK',
        'numeric' => '578',
        'symbol' => 'NOK',
        'exp' => 2,
        'country' => [
            'AQ',
            'BV',
            'NO',
            'SJ',
        ],
    ],
    [
        'name' => 'Nepalese Rupee',
        'alpha' => 'NPR',
        'numeric' => '524',
        'symbol' => 'रु.',
        'exp' => 2,
        'country' => 'NP',
    ],
    [
        'name' => 'New Zealand Dollar',
        'alpha' => 'NZD',
        'numeric' => '554',
        'symbol' => 'NZ$',
        'exp' => 2,
        'country' => [
            'CK',
            'NU',
            'NZ',
            'PN',
            'TK',
        ],
    ],
    [
        'name' => 'Omani Rial',
        'alpha' => 'OMR',
        'numeric' => '512',
        'symbol' => '.ر.ع',
        'exp' => 3,
        'country' => 'OM',
    ],
    [
        'name' => 'Panamanian Balboa',
        'alpha' => 'PAB',
        'numeric' => '590',
        'symbol' => 'PAB',
        'exp' => 2,
        'country' => 'PA',
    ],
    [
        'name' => 'Peruvian Nuevo Sol',
        'alpha' => 'PEN',
        'numeric' => '604',
        'symbol' => 'PEN',
        'exp' => 2,
        'country' => 'PE',
    ],
    [
        'name' => 'Papua New Guinean Kina',
        'alpha' => 'PGK',
        'numeric' => '598',
        'symbol' => 'PGK',
        'exp' => 2,
        'country' => 'PG',
    ],
    [
        'name' => 'Philippine Peso',
        'alpha' => 'PHP',
        'numeric' => '608',
        'symbol' => '₱',
        'exp' => 2,
        'country' => 'PH',
    ],
    [
        'name' => 'Pakistani Rupee',
        'alpha' => 'PKR',
        'numeric' => '586',
        'symbol' => 'PKR',
        'exp' => 2,
        'country' => 'PK',
    ],
    [
        'name' => 'Polish Zloty',
        'alpha' => 'PLN',
        'numeric' => '985',
        'symbol' => 'zł',
        'exp' => 2,
        'country' => 'PL',
    ],
    [
        'name' => 'Paraguayan Guarani',
        'alpha' => 'PYG',
        'numeric' => '600',
        'symbol' => '₲',
        'exp' => 0,
        'country' => 'PY',
    ],
    [
        'name' => 'Qatari Rial',
        'alpha' => 'QAR',
        'numeric' => '634',
        'symbol' => '.ر.ق',
        'exp' => 2,
        'country' => 'QA',
    ],
    [
        'name' => 'Romanian Leu',
        'alpha' => 'RON',
        'numeric' => '946',
        'symbol' => 'RON',
        'exp' => 2,
        'country' => 'RO',
    ],
    [
        'name' => 'Serbian Dinar',
        'alpha' => 'RSD',
        'numeric' => '941',
        'symbol' => 'RSD',
        'exp' => 2,
        'country' => 'RS',
    ],
    [
        'name' => 'Russian Ruble',
        'alpha' => 'RUB',
        'numeric' => '643',
        'symbol' => '₽',
        'exp' => 2,
        'country' => 'RU',
    ],
    [
        'name' => 'Rwandan Franc',
        'alpha' => 'RWF',
        'numeric' => '646',
        'symbol' => 'R₣',
        'exp' => 0,
        'country' => 'RW',
    ],
    [
        'name' => 'Saudi Riyal',
        'alpha' => 'SAR',
        'numeric' => '682',
        'symbol' => '.ر.س',
        'exp' => 2,
        'country' => 'SA',
    ],
    [
        'name' => 'Solomon Islands Dollar',
        'alpha' => 'SBD',
        'numeric' => '090',
        'symbol' => 'SI$',
        'exp' => 2,
        'country' => 'SB',
    ],
    [
        'name' => 'Seychelles Rupee',
        'alpha' => 'SCR',
        'numeric' => '690',
        'symbol' => 'SCR',
        'exp' => 2,
        'country' => 'SC',
    ],
    [
        'name' => 'Sudanese Pound',
        'alpha' => 'SDG',
        'numeric' => '938',
        'symbol' => 'ج.س',
        'exp' => 2,
        'country' => 'SD',
    ],
    [
        'name' => 'Swedish Krona',
        'alpha' => 'SEK',
        'numeric' => '752',
        'symbol' => 'SEK',
        'exp' => 2,
        'country' => 'SE',
    ],
    [
        'name' => 'Singapore Dollar',
        'alpha' => 'SGD',
        'numeric' => '702',
        'symbol' => 'S$',
        'exp' => 2,
        'country' => [
            'BN',
            'SG',
        ],
    ],
    [
        'name' => 'Saint Helena Pound',
        'alpha' => 'SHP',
        'numeric' => '654',
        'symbol' => 'SHP',
        'exp' => 2,
        'country' => 'SH',
    ],
    [
        'name' => 'Sierra Leonean Leone (old)',
        'alpha' => 'SLL',
        'numeric' => '694',
        'symbol' => 'SLL',
        'exp' => 2,
        'country' => 'SL',
    ],
    [
        'name' => 'Sierra Leonean Leone (new)',
        'alpha' => 'SLE',
        'numeric' => '925',
        'symbol' => 'SLE',
        'exp' => 2,
        'country' => 'SL',
    ],
    [
        'name' => 'Somali Shilling',
        'alpha' => 'SOS',
        'numeric' => '706',
        'symbol' => 'SOS',
        'exp' => 2,
        'country' => 'SO',
    ],
    [
        'name' => 'Surinamese Dollar',
        'alpha' => 'SRD',
        'numeric' => '968',
        'symbol' => 'Sur$',
        'exp' => 2,
        'country' => 'SR',
    ],
    [
        'name' => 'South Sudanese Pound',
        'alpha' => 'SSP',
        'numeric' => '728',
        'symbol' => 'SSP',
        'exp' => 2,
        'country' => 'SS',
    ],
    [
        'name' => 'São Tomé and Principe Dobra',
        'alpha' => 'STN',
        'numeric' => '930',
        'symbol' => 'STN',
        'exp' => 2,
        'country' => 'ST',
    ],
    [
        'name' => 'Syrian Pound',
        'alpha' => 'SYP',
        'numeric' => '760',
        'symbol' => 'ل.س',
        'exp' => 2,
        'country' => 'SY',
    ],
    [
        'name' => 'Swazi Lilangeni',
        'alpha' => 'SZL',
        'numeric' => '748',
        'symbol' => 'SZL',
        'exp' => 2,
        'country' => 'SZ',
    ],
    [
        'name' => 'Thai Baht',
        'alpha' => 'THB',
        'numeric' => '764',
        'symbol' => '฿',
        'exp' => 2,
        'country' => 'TH',
    ],
    [
        'name' => 'Tajikistani Somoni',
        'alpha' => 'TJS',
        'numeric' => '972',
        'symbol' => 'TJS',
        'exp' => 2,
        'country' => 'TJ',
    ],
    [
        'name' => 'Turkmenistani Manat',
        'alpha' => 'TMT',
        'numeric' => '934',
        'symbol' => 'TMT',
        'exp' => 2,
        'country' => 'TM',
    ],
    [
        'name' => 'Tunisian Dinar',
        'alpha' => 'TND',
        'numeric' => '788',
        'symbol' => '.د.ت',
        'exp' => 3,
        'country' => 'TN',
    ],
    [
        'name' => 'Tongan Paʻanga',
        'alpha' => 'TOP',
        'numeric' => '776',
        'symbol' => 'T$',
        'exp' => 2,
        'country' => 'TO',
    ],
    [
        'name' => 'Turkish Lira',
        'alpha' => 'TRY',
        'numeric' => '949',
        'symbol' => '₺',
        'exp' => 2,
        'country' => 'TR',
    ],
    [
        'name' => 'Trinidad and Tobago Dollar',
        'alpha' => 'TTD',
        'numeric' => '780',
        'symbol' => 'TT$',
        'exp' => 2,
        'country' => 'TT',
    ],
    [
        'name' => 'New Taiwan Dollar',
        'alpha' => 'TWD',
        'numeric' => '901',
        'symbol' => 'NT$',
        'exp' => 2,
        'country' => 'TW',
    ],
    [
        'name' => 'Tanzanian Shilling',
        'alpha' => 'TZS',
        'numeric' => '834',
        'symbol' => 'TZS',
        'exp' => 2,
        'country' => 'TZ',
    ],
    [
        'name' => 'Ukrainian Hryvnia',
        'alpha' => 'UAH',
        'numeric' => '980',
        'symbol' => '₴',
        'exp' => 2,
        'country' => 'UA',
    ],
    [
        'name' => 'Ugandan Shilling',
        'alpha' => 'UGX',
        'numeric' => '800',
        'symbol' => 'UGX',
        'exp' => 0,
        'country' => 'UG',
    ],
    [
        'name' => 'US Dollar',
        'alpha' => 'USD',
        'numeric' => '840',
        'symbol' => '$',
        'exp' => 2,
        'country' => [
            'AS',
            'BQ',
            'EC',
            'FM',
            'GU',
            'MF',
            'MH',
            'MP',
            'PR',
            'PW',
            'SV',
            'TC',
            'TL',
            'UM',
            'US',
            'VG',
            'VI',
            'ZW',
        ],
    ],
    [
        'name' => 'Uruguayan Peso',
        'alpha' => 'UYU',
        'numeric' => '858',
        'symbol' => '$U',
        'exp' => 2,
        'country' => 'UY',
    ],
    [
        'name' => 'Uzbekistan Som',
        'alpha' => 'UZS',
        'numeric' => '860',
        'symbol' => 'UZS',
        'exp' => 2,
        'country' => 'UZ',
    ],
    [
        'name' => 'Venezuelan Bolívar',
        'alpha' => 'VES',
        'numeric' => '928',
        'symbol' => 'VES',
        'exp' => 2,
        'country' => 'VE',
    ],
    [
        'name' => 'Vietnamese Dong',
        'alpha' => 'VND',
        'numeric' => '704',
        'symbol' => 'đ',
        'exp' => 0,
        'country' => 'VN',
    ],
    [
        'name' => 'Vanuatu Vatu',
        'alpha' => 'VUV',
        'numeric' => '548',
        'symbol' => 'VUV',
        'exp' => 0,
        'country' => 'VU',
    ],
    [
        'name' => 'Samoan Tala',
        'alpha' => 'WST',
        'numeric' => '882',
        'symbol' => 'WS$',
        'exp' => 2,
        'country' => 'WS',
    ],
    [
        'name' => 'CFA Franc BEAC',
        'alpha' => 'XAF',
        'numeric' => '950',
        'symbol' => 'XAF',
        'exp' => 0,
        'country' => [
            'CF',
            'CG',
            'CM',
            'GA',
            'GQ',
            'TD',
        ],
    ],
    [
        'name' => 'East Caribbean Dollar',
        'alpha' => 'XCD',
        'numeric' => '951',
        'symbol' => 'EC$',
        'exp' => 2,
        'country' => [
            'AG',
            'AI',
            'DM',
            'GD',
            'KN',
            'LC',
            'MS',
            'VC',
        ],
    ],
    [
        'name' => 'CFA Franc BCEAO',
        'alpha' => 'XOF',
        'numeric' => '952',
        'symbol' => 'XOF',
        'exp' => 0,
        'country' => [
            'BJ',
            'BF',
            'CI',
            'GW',
            'ML',
            'NE',
            'SN',
            'TG',
        ],
    ],
    [
        'name' => 'CFP Franc',
        'alpha' => 'XPF',
        'numeric' => '953',
        'symbol' => 'XPF',
        'exp' => 0,
        'country' => [
            'NC',
            'PF',
            'WF',
        ],
    ],
    [
        'name' => 'Yemeni Rial',
        'alpha' => 'YER',
        'numeric' => '886',
        'symbol' => '.ر.ي',
        'exp' => 2,
        'country' => 'YE',
    ],
    [
        'name' => 'South African Rand',
        'alpha' => 'ZAR',
        'numeric' => '710',
        'symbol' => 'ZAR',
        'exp' => 2,
        'country' => [
            'NA',
            'LS',
            'SZ',
            'ZA',
            'ZW',
        ],
    ],
    [
        'name' => 'Zambian Kwacha',
        'alpha' => 'ZMW',
        'numeric' => '967',
        'symbol' => 'ZMW',
        'exp' => 2,
        'country' => 'ZM',
    ],
    [
        'name' => 'Zimbabwe Gold',
        'alpha' => 'ZWG',
        'numeric' => '924',
        'symbol' => 'ZWG',
        'exp' => 2,
        'country' => 'ZW',
    ],
]);