<?php return [
    "basic" => [
        "available_currencies" => [
            0 => "UAH",
            1 => "EUR",
            2 => "USD",
        ],
        "catalog_root" => 1,
        "deliveries_on" => 1,
        "friendlyUrlSuffix" => "",
        "in_main_menu" => 1,
        "integrations_on" => 0,
        "main_currency" => "EUR",
        "main_menu_order" => 11,
        "orders_on" => 1,
        "payments_on" => 1,
        "search" => "blurred",
        "wishlist_on" => 1,
    ],
    "currencies" => [
        "UAH" => [
            "name" => "Ukrainian Hryvnia",
            "symbol" => "₴",
            "show" => 1,
            "position" => "before",
            "thousands" => "&nbsp;",
            "decimals" => ".",
            "exp" => 2,
        ],
        "EUR" => [
            "name" => "Euro",
            "symbol" => "€",
            "show" => 0,
            "position" => "before",
            "thousands" => "&nbsp;",
            "decimals" => ".",
            "exp" => 2,
        ],
        "USD" => [
            "name" => "US Dollar",
            "symbol" => "$",
            "show" => 0,
            "position" => "before",
            "thousands" => "&nbsp;",
            "decimals" => ".",
            "exp" => 2,
        ],
    ],
    "product" => [
        "available_modes" => [
            0 => 0,
            1 => 1,
        ],
        "inventory_on" => 2,
        "link_rule" => "category",
        "rating_on" => 1,
        "show_field_availability" => 1,
        "show_field_categories" => 1,
        "show_field_height" => 1,
        "show_field_length" => 1,
        "show_field_price" => 1,
        "show_field_price_opt" => 0,
        "show_field_price_opt_special" => 0,
        "show_field_price_special" => 1,
        "show_field_relevant" => 1,
        "show_field_sku" => 1,
        "show_field_volume" => 1,
        "show_field_weight" => 1,
        "show_field_width" => 1,
        "views_on" => 1,
        "visual_editor_introtext" => 0,
    ],
    "products" => [
        "show_field_availability" => 1,
        "show_field_category" => 1,
        "show_field_height" => 0,
        "show_field_id" => 0,
        "show_field_inventory" => 1,
        "show_field_length" => 0,
        "show_field_price" => 1,
        "show_field_price_opt" => 0,
        "show_field_price_opt_special" => 0,
        "show_field_price_special" => 1,
        "show_field_rating" => 1,
        "show_field_sku" => 1,
        "show_field_views" => 1,
        "show_field_visibility" => 1,
        "show_field_volume" => 0,
        "show_field_weight" => 0,
        "show_field_width" => 0,
    ],
];